CREATE TABLE ADVENTURE_TRIP(
    TRIP_ID INTEGER PRIMARY KEY,
    TRIP_NAME VARCHAR(100),
    START_LOCATION TEXT,
    STATE TEXT,
    DISTANCE NUMBER,
    MAX_GRP_SIZE NUMBER,
    TYPE TEXT,
    SEASON TEXT
);

-- b) INSERT INTO ADVENTURE_TRIP (TRIP_ID, TRIP_NAME, START_LOCATION, STATE, DISTANCE, MAX_GRP_SIZE, TYPE, SEASON)
--VALUES (45, 'Jay Peak', 'Jay', 'VT', 8, 8, 'Hiking', 'Summer');

PRAGMA table_info(ADVENTURE_TRIP);

--b)SELECT * FROM ADVENTURE_TRIP;

--c)DROP TABLE ADVENTURE_TRIP;
