-- ACANTILADO, MARIA ANGELICA
-- DYTIANQUIN, CHALZEA FRANSEN C.

-- a)
CREATE TABLE ADVENTURE_TRIP(
    TRIP_ID INTEGER PRIMARY KEY,
    TRIP_NAME VARCHAR(75),
    START_LOCATION CHAR(50),
    STATE CHAR(2),
    DISTANCE NUMBER,
    MAX_GRP_SIZE NUMBER,
    TYPE CHAR(20),
    SEASON CHAR(20)
);

PRAGMA table_info(ADVENTURE_TRIP);

-- b) 

INSERT INTO ADVENTURE_TRIP (TRIP_ID, TRIP_NAME, START_LOCATION, STATE, DISTANCE, MAX_GRP_SIZE, TYPE, SEASON)
VALUES (45, 'Jay Peak', 'Jay', 'VT', 8, 8, 'Hiking', 'Summer');

SELECT * FROM ADVENTURE_TRIP;

-- c)

DROP TABLE ADVENTURE_TRIP;

